substitutions:
  name: sonoff-s31
  friendly_name: Sonoff S31
  append_mac: true
  ssid: "sonoff-s31"
  password: "12345678"
  fallback_ssid: "sonoff-s31-setup"
  fallback_password: "12345678"
  webuser: "admin"
  webpass: "12345678"
  timezone: "Europe/Sofia"

dashboard_import:
  package_import_url: github://raylee930/s31-esphome/sonoff-s31-lite.yaml
  import_full_config: false

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${append_mac}
  project:
    name: "Sonoff.S31-Lite"
    version: "2025.12.0"

esp8266:
  board: esp01_1m
  framework:
    version: recommended
  restore_from_flash: true

api:
  reboot_timeout: 0s
    
ota:
  platform: esphome

wifi:
  ssid: "${ssid}"
  password: "${password}"
  min_auth_mode: WPA2
  ap:
    ssid: "${fallback_ssid}"
    password: "${fallback_password}"

captive_portal:

web_server:
  port: 80
  version: 3
  local: true
  ota: false
  auth:
    username: "${webuser}"
    password: "${webpass}"

logger:
  baud_rate: 0
  logs:
    sensor: DEBUG

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "Button"
    internal: true
    on_press:
      - switch.toggle: relay

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: "mdi:ip-network"
    mac_address:
      name: "MAC Address"
      icon: "mdi:network"
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    icon: "mdi:signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "S31 Switch"
    icon: "mdi:power-plug"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: restart
    name: "Reboot"
    icon: "mdi:restart"

time:
  - platform: sntp
    id: sntp_time
    timezone: "${timezone}"
    servers:
     - pool.ntp.org
     - time.google.com
     - time.windows.com

status_led:
  pin:
    number: GPIO13
